version: '2'
services:

  app:
    image: php
    volumes:
      - ./www:/app
    command: "php -S 0.0.0.0:80 /app/index.php"

  sso:
    build: lemonldap-ng
    environment:
      - SSODOMAIN=sso.local
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./lemonldap-ng/conf/:/var/lib/lemonldap-ng/conf/
      - ./lemonldap-ng/sites-enabled/starter.conf:/etc/apache2/sites-enabled/starter.conf
